* **Let's review:** we can _import_ a module, or individual functions or constants _from_ a module.  There are many libraries out there, some of which we'll cover as we continue.
* But we can also import entirely new types of objects.

* For entirely illustrative purposes, lets consider the `turtle` module.

* For instance, perhaps we'd like to do matrix multiplication...
  * Of course, we have 2D lists, and we _could_ write the functionality ourselves... 
* But let's import the **`numpy`** module, which provides the `ndarray` `class`, and basic functionality for matrix multiplication.
  * Happens to be an important module for numerical methods -- but we won't need it much.

In [47]:
import numpy as np

a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
amat = np.array(a)

print(type(a), type(amat))

<class 'list'> <class 'numpy.ndarray'>


* `a` and `amat` are fundamentally different objects, likes ints v. floats.  The new class, `numpy.ndarray` can do things that the list could not do -- like matrix multiplication.
  * This is just as `string`s had special methods (`lower()`, `split()`, `join()`, etc.), comes with new methods/functions.

In [46]:
b = np.array([[2], [4], [6]])
b.dot(b.transpose())
b.dot(amat)

array([[60, 72, 84]])

Or get a matrix's inverse:

In [49]:
g3 = np.array([[0, 0, 1, 0], [0, 0, 0, -1], [-1, 0, 0, 0], [0, 1, 0, 0]])
g3_inv = np.linalg.inv(g3)

print(g3.dot(g3_inv))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


These `numpy.ndarrays` react very differently than lists, to multiplication and division.  

In [48]:
t_arr = np.array([-459.67, -40, 32, 98.6, 212])
print("Temperatures f to C:", (t_arr - 32) * 5/9)

Temperatures f to C: [-273.15  -40.      0.     37.    100.  ]


<font color=darkred>**The point is, there's tremendous functionality and shortcuts, that _you don't have to write_.**</font>  It should also be clear that this new objects are pretty useful.

## Iterators
You don't always have to make a fully realized list!

It often makes sense to create an iterator or generator...

### What is that!? 

Iterators and generators are objects that are 'ready' to generate the `next()` value in a sequence (they typically also have a stop value).  This is what's built in   The individual values are not stored!

In [1]:
a = (i*i for i in range(10)) # looks a lot like list comprehensions.
a

<generator object <genexpr> at 0x104f86938>

In [2]:
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))

0
1
4
9
16


In [ ]:
def fib(N): 
    n = 0
    i, j = 1, 1
    while n < N:
        n += 1
        out = i
        i = j
        j += out
        yield out
    
for x in fib(20): print(x)